algoritmo "semnome"

var
 n1,n2,n3,n4:real
 med: real
 nome: caractere
 
inicio
escreval("Escreva seu nome")
leia(nome)
escreval(Nome,(" Informe a Nota 1"))
leia(n1)
escreval("Informe a Nota 2")
leia(n2)
escreval("Informe a Nota 3")
leia(n3)
escreval("Informe a Nota 4")
leia(n4)
escreval("Calculando a media...")
med<- (n1+n2+n3+n4)/4)
escreval("Sua media é "),med
se med >=5 entao
escreval ("Aprovado")
senao
escreval ("Infelizmente você foi reprovado")
fimse
fimalgoritmo
